
title: Andres Leon Rangel Page
url: 'http://aleon.nz'
baseurl: '/Jekyll-PanelCV' #change it according to your repository name

# Profile information
yourname: Andres Leon-Rangel  ## put your name
title: 'DEVOps &amp; Software Engineer'  ## your title
location: Auckland , New Zealand

## Social Profiles
facebook: http://www.facebook.com/aleon1220  ## your facebook account url
twitter: https://twitter.com/aleon1220 ## your twitter account url
linkedin: https://www.linkedin.com/in/aleon1220/  ## your linkedin account url
# dribbble: http://www.dribble.com  ## you dribbble account url
# foursquare: http://www.foursquare.com  ## your foursquare account url

# Update all the sections by editing the files inside _includes folder.
exclude:
  # - "docker-compose-custom-ruby.yml"
  # - "docker-compose-simple-jekyll.yml"
  # - "package.json"
#   - "README.md"
#   - "publish.sh"
  - "vendor"